# vim ft=yaml
# Multiple lines can be made a single "virtual line" because of how Travis
# munges each line before executing it to print out the exit status.  It's okay
# for it to be on multiple physical lines, so long as you remember: - There
# can't be any leading "-"s - All newlines will be removed, so use ";"s

dist: xenial
sudo: true
language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
    - 3.5

script:
    - echo "Testing Azure... Don't mind me."
