# vim ft=yaml
# CI on Windows via appveyor

environment:
  matrix:
    - PYTHON: C:\Miniconda
    - PYTHON: C:\Miniconda-x64
    - PYTHON: C:\Miniconda34
    - PYTHON: C:\Miniconda34-x64
    - PYTHON: C:\Miniconda35
    - PYTHON: C:\Miniconda35-x64
    - PYTHON: C:\Miniconda36
    - PYTHON: C:\Miniconda36-x64
    - PYTHON: C:\Miniconda37
    - PYTHON: C:\Miniconda37-x64

install:
  - ls C:\
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

  # Install the dependencies of the project.
  - python -m pip install --upgrade pip setuptools wheel
  - python -m pip install numpy scipy matplotlib nose h5py mock pydicom
  - python -m pip install .
  - SET NIBABEL_DATA_DIR=%CD%\nibabel-data

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Change into an innocuous directory and find tests from installation
  - mkdir for_testing
  - cd for_testing
  # Print Python, numpy versions
  - python -c "import sys, numpy; print('Python', sys.version); print('numpy', numpy.__version__)"
  # Show all environment variables to ease possible future debugging
  - set
  - nosetests --with-doctest nibabel
