
parameters:
  name: ''
  vmImage: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    EXTRA_WHEELS: "https://5cf40426d9f06eb7461d-6fe47d9331aba7cd62fc36c7196769e4.ssl.cf2.rackcdn.com"
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(PYTHON_VERSION)'
        addToPath: true
        architecture: '$(PYTHON_ARCH)'
    - script: |
        python -c "import random; print(random.randint(0, 4294967295))" > hashseed.txt
        SET /p PYTHONHASHSEED=<hashseed.txt
        echo %PYTHONHASHSEED%
      displayName: 'Generate hash seed'
    - script: |
        python -m pip install --upgrade pip setuptools>=30.3.0 wheel
      displayName: 'Update build tools'
    - script: |
        python -m pip install --find-links %EXTRA_WHEELS% numpy scipy matplotlib h5py pydicom
        python -m pip install nose mock coverage codecov
      displayName: 'Install dependencies'
    - script: |
        python -m pip install .
        SET NIBABEL_DATA_DIR=%CD%\\nibabel-data
      displayName: 'Install nibabel'
    - script: |
        mkdir for_testing
        cd for_testing
        cp ../.coveragerc .
        SET /p PYTHONHASHSEED=<hashseed.txt
        echo %PYTHONHASHSEED%
        nosetests --with-doctest --with-coverage --cover-package nibabel nibabel
      displayName: 'Nose tests'
    - script: |
        cd for_testing
        codecov
      displayName: 'Upload To Codecov'
      env:
        CODECOV_TOKEN: $(CODECOV_TOKEN)
